name: Undeploy PR preview

on: 
  pull_request:
    types: 
      - unlabeled
      - closed

env:
  IMAGE_NAME: sledilnik-web
  DEPLOYMENT_NAMESPACE: sledilnik-pr

jobs:
  undeploy:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'deploy-preview') || github.event.action == 'closed' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: undeploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm uninstall -n ${{ env.DEPLOYMENT_NAMESPACE }} pr-${{ github.event.pull_request.number }}-website ./helm-chart || true
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: delete deployment
        uses: strumwolf/delete-deployment-environment@v1.01
        with:
          token: ${{ github.token }}
          environment: pr-${{ github.event.pull_request.number }}