# action.yml
name: 'Deploy'
description: 'Helm deploy action'
inputs:
  releaseName:
    description: 'Helm release name'
    required: true
  chartName:
    description: 'Chart name'
    required: true
  chartVersion:
    description: 'Chart version'
    required: false
  namespace:
    description: 'Kubernetes namespace to deploy to'
    required: false
    default: 'default'
  kubeconfig:
    description: 'Kubeconfig'
    required: true
  token:
    description: 'Github token'
    required: false
    default: ${{ github.token }}
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
