name: Build container image

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [synchronize, reopened, labeled]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: Setup environment
        id: envsetup
        uses: ./.github/actions/envsetup

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      # - name: build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     context: .
      #     file: ./Dockerfile-new
      #     tags: |
      #       ghcr.io/${{ github.repository_owner }}/website:${{ env.IMAGE_TAG}}

      - name: Deploy
        id: deploy
        uses: ./.github/actions/deploy
        with:
          releaseName: ${{ steps.envsetup.ReleaseName }}
          chartName: website